spring:
    application:
        name: Product

    datasource:
        url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:productdb}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
        username: ${DB_USER:productuser}
        password: ${DB_PASSWORD:productpass}
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect

server:
    port: ${SERVER_PORT:8082}

---
spring:
    config:
        activate:
            on-profile: test
    datasource:
        url: jdbc:h2:mem:productdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        driver-class-name: org.h2.Driver
        username: sa
        password:
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.H2Dialect
