services:
  order-db:
    image: mysql:8.0
    container_name: order-db
    restart: always
    environment:
      MYSQL_DATABASE: orderdb
      MYSQL_USER: orderuser
      MYSQL_PASSWORD: orderpass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3309:3306"
    volumes:
      - order-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  order-service:
    image: order-service:latest
    container_name: order-service
    restart: always
    ports:
      - "8083:8083"
    environment:
      SERVER_PORT: 8083
      DB_HOST: order-db
      DB_PORT: 3306
      DB_NAME: orderdb
      DB_USER: orderuser
      DB_PASSWORD: orderpass
    depends_on:
      - order-db

volumes:
    order-data:

