services:
  order-db:
    image: mysql:8.0
    container_name: order-db
    restart: always
    environment:
      MYSQL_DATABASE: orderdb
      MYSQL_USER: orderuser
      MYSQL_PASSWORD: orderpass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3309:3306"
    volumes:
      - order-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  order-data:
