spring:
  datasource:
    url: jdbc:mysql://mysql-order:3309/orderdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: orderuser
    password: orderpass
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8083
