name: CI/CD Microservices

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      SERVER_PORT: 8082

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build and Test ProductService
        working-directory: ProductService
        run: |
          echo "===== Using in-memory H2 DB ====="
          mvn clean install -Dspring.profiles.active=test

      - name: Build and Test OrderService
        working-directory: OrderService
        run: |
          echo "===== Using in-memory H2 DB for OrderService ====="
          mvn clean install -Dspring.profiles.active=test
