name: CI/CD Microservices

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [ProductService, OrderService, UserService]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build and Test ${{ matrix.service }}
        working-directory: ${{ matrix.service }}
        run: |
          echo "===== Building and Testing ${{ matrix.service }} using in-memory H2 DB ====="
          mvn clean install -Dspring.profiles.active=test
