name: CI/CD Microservices

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mysql-product:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: productpass
          MYSQL_DATABASE: productdb
          MYSQL_USER: productuser
          MYSQL_PASSWORD: productpass
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DB_HOST: mysql-product
      DB_PORT: 3306
      DB_NAME: productdb
      DB_USER: productuser
      DB_PASSWORD: productpass
      SERVER_PORT: 8082

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Wait for MySQL to be ready
        run: |
          for i in {1..10}; do
            if mysqladmin ping -h "127.0.0.1" --port=3306 --password=productpass --silent; then
              echo "✅ MySQL is ready!"
              break
            fi
            echo "⏳ Waiting for MySQL..."
            sleep 5
          done

      - name: Build and Test ProductService
        working-directory: ProductService
        run: |
          echo "===== Environment Variables ====="
          echo "DB_HOST = $DB_HOST"
          echo "DB_PORT = $DB_PORT"
          echo "DB_NAME = $DB_NAME"
          echo "DB_USER = $DB_USER"
          echo "DB_PASSWORD = $DB_PASSWORD"
          echo "================================="
          
          mvn clean install -Dspring.profiles.active=test